//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSorunBildirim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basvuru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Basvuru()
        {
            this.Cevaplar = new HashSet<Cevaplar>();
            this.Dokumanlar = new HashSet<Dokumanlar>();
            this.Kanit = new HashSet<Kanit>();
            this.Sevk = new HashSet<Sevk>();
        }
    
        public int Basvuru_Id { get; set; }
        public string Basvuru_Durumu { get; set; }
        public string Dogrulanan_Kisi { get; set; }
        public Nullable<int> Kurum_Id { get; set; }
        public Nullable<int> Yetkili_Id { get; set; }
        public bool Is_Active { get; set; }
        public string Konu { get; set; }
        public string Sikayet { get; set; }
        public string Adres { get; set; }
        public string AdSoyad { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Enlem { get; set; }
        public string Dogrulama_Kodu { get; set; }
        public string Boylam { get; set; }
    
        public virtual Kurum Kurum { get; set; }
        public virtual Yetkililer Yetkililer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cevaplar> Cevaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokumanlar> Dokumanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kanit> Kanit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sevk> Sevk { get; set; }
    }
}
