//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSorunBildirim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumanlar
    {
        public int Dokuman_Id { get; set; }
        public string Dosya_Adi { get; set; }
        public string Dosya_Tipi { get; set; }
        public Nullable<int> Dosya_Boyutu { get; set; }
        public Nullable<int> Basvuru_Id { get; set; }
        public bool Is_Active { get; set; }
    
        public virtual Basvuru Basvuru { get; set; }
    }
}
