//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSorunBildirim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurum_Yetkili
    {
        public int Kurum_Yetkili_Id { get; set; }
        public Nullable<int> Kurum_Id { get; set; }
        public Nullable<int> Yetkili_Id { get; set; }
        public bool Is_Active { get; set; }
    
        public virtual Kurum Kurum { get; set; }
        public virtual Yetkililer Yetkililer { get; set; }
    }
}
