//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSorunBildirim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loglar
    {
        public int Log_Id { get; set; }
        public string Tablo_Adi { get; set; }
        public Nullable<System.DateTime> Degisim_Zamani { get; set; }
        public string Ip_Adresi { get; set; }
        public Nullable<int> Kullanıcı_Id { get; set; }
        public string Log_Detay { get; set; }
        public bool Is_Active { get; set; }
    }
}
