//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSorunBildirim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sevk
    {
        public int Sevk_Id { get; set; }
        public Nullable<System.DateTime> Sevk_Zamani { get; set; }
        public Nullable<int> Basvuru_Id { get; set; }
        public Nullable<int> Birim_Id { get; set; }
        public bool Is_Active { get; set; }
    
        public virtual Basvuru Basvuru { get; set; }
        public virtual Birim Birim { get; set; }
    }
}
